import io
from datetime import datetime
from reportlab.lib import colors
from reportlab.lib.pagesizes import letter
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, HRFlowable, KeepTogether

BLUE = colors.HexColor("#1a3a5c")
GRAY = colors.HexColor("#f5f5f5")
SEV = {"critical":colors.HexColor("#c0392b"),"high":colors.HexColor("#e67e22"),"medium":colors.HexColor("#f1c40f"),"low":colors.HexColor("#27ae60")}

def styles():
    b = getSampleStyleSheet()
    return {k:ParagraphStyle(k,parent=b[p],**kw) for k,p,kw in [
        ("title","Title",{"fontSize":20,"textColor":BLUE}),
        ("h1","Heading1",{"fontSize":14,"textColor":BLUE,"spaceBefore":10}),
        ("h2","Heading2",{"fontSize":11,"textColor":BLUE,"spaceBefore":8}),
        ("body","Normal",{"fontSize":9,"leading":13}),
        ("bullet","Normal",{"fontSize":9,"leading":13,"leftIndent":15}),
        ("small","Normal",{"fontSize":8,"textColor":colors.gray}),
        ("code","Code",{"fontSize":8,"fontName":"Courier","backColor":GRAY,"leftIndent":10}),
    ]}

class PDFGenerator:
    def generate(self, alert_text, analysis, techniques_detail, mitigations):
        buf = io.BytesIO()
        doc = SimpleDocTemplate(buf, pagesize=letter, leftMargin=.75*inch, rightMargin=.75*inch, topMargin=.75*inch, bottomMargin=.75*inch)
        s = styles(); story = []
        story += [Paragraph("Threat Mitigation Report",s["title"]),
                  Paragraph(f"Generated: {datetime.utcnow().strftime('%Y-%m-%d %H:%M UTC')}",s["small"]),
                  HRFlowable(width="100%",thickness=2,color=BLUE,spaceAfter=8)]
        sev = analysis.get("severity","unknown").lower()
        st = Table([[Paragraph(f"Severity: {sev.upper()}",ParagraphStyle("sv",fontSize=11,textColor=colors.white,fontName="Helvetica-Bold"))]],colWidths=[2*inch])
        st.setStyle(TableStyle([("BACKGROUND",(0,0),(-1,-1),SEV.get(sev,colors.gray)),("ALIGN",(0,0),(-1,-1),"CENTER"),("TOPPADDING",(0,0),(-1,-1),6),("BOTTOMPADDING",(0,0),(-1,-1),6)]))
        story += [st, Spacer(1,8), Paragraph("Executive Summary",s["h1"]),
                  Paragraph(analysis.get("summary",""),s["body"]), Spacer(1,8),
                  Paragraph("Original Alert",s["h1"]),
                  Paragraph(alert_text[:1200].replace("\n","<br/>"),s["code"]), Spacer(1,8)]
        techs = analysis.get("techniques",[])
        if techs:
            story.append(Paragraph("MITRE ATT&amp;CK Techniques",s["h1"]))
            rows = [["ID","Name","Confidence","Tactics"]]
            for t in techs:
                d = next((x for x in techniques_detail if x.get("id")==t.get("id")),{})
                rows.append([t.get("id",""),Paragraph(t.get("name",""),s["body"]),t.get("confidence",""),Paragraph(", ".join(d.get("tactics",[])),s["body"])])
            tbl = Table(rows,colWidths=[.9*inch,2.3*inch,.9*inch,2.4*inch])
            tbl.setStyle(TableStyle([("BACKGROUND",(0,0),(-1,0),BLUE),("TEXTCOLOR",(0,0),(-1,0),colors.white),("FONTSIZE",(0,0),(-1,-1),8),("GRID",(0,0),(-1,-1),.5,colors.lightgrey),("VALIGN",(0,0),(-1,-1),"TOP")]))
            story += [tbl, Spacer(1,10)]
        story.append(Paragraph("Remediation Checklists",s["h1"]))
        for t in techs:
            tid = t.get("id",""); m = mitigations.get(tid,{})
            sec = [Paragraph(f"{tid} — {t.get('name','')}",s["h2"])]
            if t.get("rationale"): sec.append(Paragraph(f"<i>{t['rationale']}</i>",s["body"]))
            if m and "error" not in m:
                for key,lbl in [("immediate_actions","Immediate"),("short_term","Short-Term"),("long_term","Long-Term")]:
                    for item in m.get(key,[]): sec.append(Paragraph(f"• [{lbl}] {item}",s["bullet"]))
                for rule in m.get("detection_rules",[]): sec.append(Paragraph(rule,s["code"]))
            d = next((x for x in techniques_detail if x.get("id")==tid),{})
            if d.get("url"): sec.append(Paragraph(d["url"],s["small"]))
            sec += [Spacer(1,6),HRFlowable(width="100%",thickness=.5,color=colors.lightgrey)]
            story.append(KeepTogether(sec))
        story.append(Paragraph("Generated by MS Sentinel Threat Mitigation App — Claude AI",s["small"]))
        doc.build(story)
        return buf.getvalue()
